language: node_js

dist: trusty

node_js:
  - "lts/*"

cache:
  directories:
    - ~/.npm
    - ~/.cache

addons:
  chrome: stable
  firefox: latest
  apt:
    packages:
      - libgconf-2-4

notifications:
  email: false

install:
  - npm install
  - npm run build

script:
  - npm run test:ci

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "main" && bash deploy.sh

branches:
  only:
    - main
    - /^greenkeeper/.*$/

env:
  global:
    secure: U9Oy8posoZq1sd9nUqbnqTr5b+AQtbegtjjzbCuAaI89cdEuA4o+cYWo07e6E9AictGddFRQpz5JEBmMWeqDIuVYCoqIs1brfkplFM6jf1KI56KwFrBareKcwu7n8pHBtHun9l9sLIJNrvXFPtI4IUiVz0l6Y0pOkNPDxTEZbNuLzcaEfQ56E4TG1hnEkoKwUuDU1Qz4cSWUETeBe53dXmgKCacIbdqLJboIdGUzblQIUU7Psl4bbi4UsE7DyoWp+L1u4Gt7YT1yhV/pTgybOxVDZSEC3wl3TkrlJYNQ3y9EYGaKdTuiDo/WRb/3qgW0Uot+jU0uJO1ozHJfhGppH54RKZA4rC5F0OwjisiNvPAHnFpQBYInvGrxL60WEE+isnmxZeFgJdE5e++944EYATiRM+PhbNYsW1Zj7FVMyhJntShid66XPAQAikVQW8qZcKGzH/1lTw/2/cQf1mfZDpOpG6LW7Xds4hj8GrmyPTKuy8O67axBqCV/N2sOoA/Ve+uTWBfHZnaGOqzZ6j4ooTyBlfQzdsDNIMnUCNX4cauV30CLHjw1FHkim3gIR9Npe82mWqbZg+kddBnbmDKJ09wYSU9XNr5xYr1K6xUduJ4dWHTktv1NV6pnFigw2QgQ6N9vfLQIcare30kOY09KGkUEPDjWAzum9aodS/NgY0U=
